name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK version
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Show files before maven build
        run: tree -L 5

      - name: Build App
        run: mvn clean install

      - name: Show files after maven build
        run: tree -L 5